FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY . .

RUN pnpm install --frozen-lockfile=false

WORKDIR /app/frontend

RUN pnpm run build

EXPOSE 80

CMD ["pnpm", "preview", "--host", "0.0.0.0", "--port", "80"]
