import { TutorialStep } from './types';

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'dashboard-welcome',
    targetSelector: '#tutorial-welcome-banner',
    route: '/',
    badge: 'Overview',
    title: 'Welcome to Language Learner!',
    description:
      'Language Learner is your personal AI language tutor. It generates tailored lessons, tracks vocabulary, and grades your handwritten or typed exercises in real time. Let’s take a quick 1-minute tour of all features!',
    placement: 'bottom',
    iconName: 'Sparkles',
    highlightPadding: 12,
    scrollBlock: 'top',
  },
  {
    id: 'settings-ai-key',
    targetSelector: '#tutorial-ai-config',
    route: '/settings',
    badge: 'Crucial Setup',
    title: '1. Configure Your AI API Key',
    description:
      'To generate daily lessons and get intelligent grading, enter your API key here (e.g. OpenAI, Google Gemini, Claude, Groq). Your key is securely encrypted with AES-256-GCM in the database and is never exposed to the browser.',
    placement: 'bottom',
    iconName: 'Key',
    highlightPadding: 12,
    scrollBlock: 'start',
    scrollOffset: 70,
  },
  {
    id: 'settings-presets',
    targetSelector: '#tutorial-provider-presets',
    route: '/settings',
    badge: 'AI Providers',
    title: '2. Select AI Provider & Model',
    description:
      'Easily switch between providers! Click any preset chip (OpenAI, Gemini, Claude, Groq, Mistral, or local Ollama) to automatically fill in the endpoint URL and suggested models.',
    placement: 'bottom',
    iconName: 'Cpu',
    highlightPadding: 12,
    scrollBlock: 'start',
    scrollOffset: 70,
  },
  {
    id: 'settings-languages',
    targetSelector: '#tutorial-language-prefs',
    route: '/settings',
    badge: 'Preferences',
    title: '3. Choose Your Languages',
    description:
      'Set your native language and target language. All lesson generation, vocabulary tracking, practice exercises, audio pronunciation, and AI feedback dynamically adapt to your selection.',
    placement: 'bottom',
    iconName: 'Globe',
    highlightPadding: 12,
    scrollBlock: 'top',
  },
  {
    id: 'dashboard-start-lesson',
    targetSelector: '#tutorial-start-lesson-btn',
    route: '/',
    badge: 'Daily Practice',
    title: 'Start Daily Lesson',
    description:
      'Whenever you are ready to study, click "Start Daily Lesson" on your Dashboard to generate tailored grammar rules, interactive exercises, and vocabulary practice.',
    placement: 'bottom',
    iconName: 'Sparkles',
    highlightPadding: 10,
    scrollBlock: 'top',
  },
  {
    id: 'lesson-proposals',
    targetSelector: '#tutorial-lesson-container',
    route: '/lessons/new',
    badge: 'Lesson Generation',
    title: 'AI Rule Proposals & Word Count',
    description:
      'The AI proposes 3 grammar rules tailored to your proficiency. You can change target new words (3, 5, 7, 10) or click the refresh icon on any card to get a different proposal.',
    placement: 'top',
    iconName: 'Scroll',
    highlightPadding: 20,
    scrollBlock: 'top',
  },
  {
    id: 'lesson-custom-rule',
    targetSelector: '#tutorial-custom-rule',
    route: '/lessons/new',
    badge: 'Custom Practice',
    title: 'Custom Topics & Spaced Review',
    description:
      'Want to learn something specific? Type any custom topic (e.g. "Ordering coffee in a café"), or choose the Spaced Repetition card below to reinforce previously learned rules.',
    placement: 'top',
    iconName: 'BookOpen',
    highlightPadding: 12,
    scrollBlock: 'center',
  },
  {
    id: 'wordbank-overview',
    targetSelector: '#tutorial-wordbank-header',
    route: '/words',
    badge: 'Word Bank',
    title: 'Vocabulary Bank & Audio',
    description:
      'Every new word introduced in lessons is automatically saved to your Word Bank. You can add custom words, filter by part of speech, and click the audio button to hear native pronunciation at normal or slow speed.',
    placement: 'bottom',
    iconName: 'Volume2',
    highlightPadding: 12,
    scrollBlock: 'top',
  },
  {
    id: 'rulebank-overview',
    targetSelector: '#tutorial-rulebank-header',
    route: '/rules',
    badge: 'Rule Bank',
    title: 'Grammar Rule Bank',
    description:
      'Browse, search, and manage all your mastered grammar rules, example sentences, and exception notes whenever you need a quick grammar reference.',
    placement: 'bottom',
    iconName: 'Scroll',
    highlightPadding: 12,
    scrollBlock: 'top',
  },
  {
    id: 'history-overview',
    targetSelector: '#tutorial-history-filter',
    route: '/history',
    badge: 'History',
    title: 'Lesson History & AI Feedback',
    description:
      'Access all past lessons, filter by grading status, review AI feedback breakdowns and score cards, or resume unfinished lessons right where you left off.',
    placement: 'bottom',
    iconName: 'Clock',
    highlightPadding: 12,
    scrollBlock: 'top',
  },
  {
    id: 'dashboard-stats',
    targetSelector: '#tutorial-stats-grid',
    route: '/',
    badge: 'Progress',
    title: 'Mastery Stats',
    description:
      'Track your learning progress at a glance: total words in bank, mastered grammar rules, completed lessons, and overall average exercise score.',
    placement: 'bottom',
    iconName: 'Award',
    highlightPadding: 12,
    scrollBlock: 'center',
  },
  {
    id: 'settings-account-replay',
    targetSelector: '#tutorial-account-card',
    route: '/settings',
    badge: 'Account & Tour',
    title: "You're All Set!",
    description:
      'You are ready to begin! You can replay this tour anytime using the "Replay Tutorial" button right here in Settings. Enter your AI API key underneath to generate your first lesson!',
    placement: 'bottom',
    iconName: 'CheckCircle2',
    highlightPadding: 12,
    scrollBlock: 'top',
  },
];
